<dependencyManagement>
       <dependencies>
           <dependency>
               <groupId>io.quarkus</groupId>
               <artifactId>quarkus-bom</artifactId>
               <version>${quarkus.version}</version>
               <type>pom</type>
               <scope>import</scope>
           </dependency>
       </dependencies>
   </dependencyManagement>